// components/UserMenu.vue
<template>
  <nav>
    <nuxt-link v-if="user.isAuthenticated" to="/account/">{{ user.username }}</nuxt-link>
    <nuxt-link v-if="!user.isAuthenticated" to="/login/">Login</nuxt-link>
  </nav>
</template>

<script>
export default {
  data({ $store }) { return { user: $store.state.user || {} } },
}
</script>

<style scoped>
  margin: 0.2em auto 1ex;
  width: 3em;
  height: 3em;

  background-color: #29A3EC;
  border-radius: 100%;

  @media (min-width: 780px) {
    display: inline-block;
  }
</style>

// src/components/UserMenu/index.jsx
import React from 'react'
import styled from 'styled-components'

export default styled(props => <div className={props.className} />)`
  margin: 0.2em auto 1ex;
  width: 3em;
  height: 3em;

  background-color: #29A3EC;
  border-radius: 100%;

  @media (min-width: 780px) {
    display: inline-block;
    width: 1.3em;
    height: 1.3em;
  }
`
